[package]
name = "gotham_examples_static_files_introduction"
description = "An example of serving static files with Gotham"
version = "0.0.0"
publish = false

[dependencies]
gotham = { path = "../../gotham" }
env_logger = "*"